### ISSUE TITLE
[BUG]Error sampling_mode.set(json_set['sampling_mode']) when running prdgui.py

### ISSUE THREAD

**Issue by softyoda** [KnoBuddy/VisualDiffusion#15]
**Describe the bug**
First install of VisualDiffusion inside of prs up to date repo
I can't run the prdgui.py

Error :
```
(prs) C:\Users\intel\Desktop\StableDiffusion\progrock-stable\prs>python visualdiffusion\prdgui.py
Default settings loaded
Traceback (most recent call last):
  File "visualdiffusion\prdgui.py", line 755, in <module>
    sampling_mode.set(json_set['sampling_mode'])
KeyError: 'sampling_mode'
```

**Desktop :**
 - OS: Windows 10
 - GPU and VRAM: rtx 3080 10gb
 - CUDA Version : IDK, I updated my nvidia drivers, but it's not the same thing as cuda sdk I belive.

**Additional context**
First run of the program, i just git-pulled prs and VisualDiffusion inside the prs folder, i'm in the conda environment for prs.

**Comment by KnoBuddy** [comment]
You are trying to run PRDGUI inside of the PRS environment/repo. They are two different diffusion models.

**Comment by KnoBuddy** [comment]
prsgui.py for ProgRock-Stable, prdgui.py for ProgrockDiffusion.

**Comment by softyoda** [comment]
Oh, you're right, I just followed the tutorial in the readme.md without noticing there were two .py for progrock diffusion and stable. 

I've tried to execute the prsgui.py and now I have the following error : 
```
(prs) C:\Users\intel\Desktop\StableDiffusion\progrock-stable\prs>python visualdiffusion\prsgui.py
Traceback (most recent call last):
  File "visualdiffusion\prsgui.py", line 694, in <module>
    set_variables()
  File "visualdiffusion\prsgui.py", line 111, in set_variables
    method = json_set.method
AttributeError: 'types.SimpleNamespace' object has no attribute 'method'
```

**Comment by KnoBuddy** [comment]
Delete gui_settings.json

**Comment by softyoda** [comment]
I don't have any gui_settings.json inside the prs directory and any other sub-directory. 
![image](https://user-images.githubusercontent.com/13988751/188339003-92226f60-8229-4489-a685-20729d40fcd0.png)

**Comment by KnoBuddy** [comment]
Delete line 111 of prsgui.py. method = json_set.method

**Comment by KnoBuddy** [comment]
I think I left an extra line in there that shouldn't be. I'm on mobile and I'll push the change when I get home if that fixes it.

**Comment by softyoda** [comment]
Yep, it was that, I deleted the line 111 ( `method = json_set.method`) and now it work ! Thanks !
