### ISSUE TITLE
[BUG] File open in another program error when using GOBIG

### ISSUE THREAD

**Issue by Johnnycyan** [KnoBuddy/VisualDiffusion#20]
**Describe the bug**
When using GOBIG sometimes the GUI will try to load one of the splits as a preview image which will cause it to be locked and cause the operation to fail

**To Reproduce**
1. Create an image with GOBIG enabled
2. Wait for it to eventually error out.
3. Observe that the image is question is being previewed in the GUI

**Expected behavior**
The GUI should not just open the newest image in the target folder. It should look for the proper name of the output file and wait for that to appear before previewing anything.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU and VRAM: 3090 24GB
 - CUDA Version 11.7

**Additional context**
The image size I'm generating is 1728x960 with a GOBIG scale of 4

**Comment by KnoBuddy** [comment]
I'll look into it. I did find errors running gobig but I was able to get the final image. I was super concerned with proper functionality of displaying the images of gobig in the GUI since, at least on my desktop anything larger than 768 along with the GUI starts to track off the screen.

**Comment by KnoBuddy** [comment]
I haven't been able to reproduce the results. Are you using prsgui.py or makegudpics.py?

**Comment by Johnnycyan** [comment]
> I haven't been able to reproduce the results. Are you using prsgui.py or makegudpics.py?

prsgui

**Comment by KnoBuddy** [comment]
I haven't been able to reproduce the issue. I tried many sessions. I did however rewrite the way that the images are displayed. It also now resizes the images if they are larger than 768 in either direction. Please let me know if your issue is solved with the new code.
