### ISSUE TITLE
[BUG] TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by WorldTeacher** [KnoBuddy/VisualDiffusion#6]
**Describe the bug**
I tried to run the gui to produce some images but got an error instead

**To Reproduce**
1. Open GUI
2. start a run 
3. See error

**Expected behavior**
The Run should start, and the images should be created.

**Screenshots**

![Gui and Settings](https://user-images.githubusercontent.com/41587052/185481544-b560e264-159f-4f6b-a27b-c112d33e0842.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux with kernel 5.19.1-arch2-1
 - GPU and VRAM: RTX 3090, 24GB
 - CUDA Version: 11.7

**Additional context**
The problem first occurred with a different error, shown here:
[original error](https://user-images.githubusercontent.com/41587052/185480332-516612d3-e4be-4214-888d-5eb5a3c86bfb.png)
but a reinstallation of NumPy fixed this. I then tested the same settings in a copy of the old GUI, which works fine
![working GUI](https://user-images.githubusercontent.com/41587052/185482012-913eea50-a131-42d1-ba3a-aca3130ca665.png)

This error seems to affect all branches except branch KnoBuddy-rebase, as this has a different error: `KeyError: simple_symmetry` 

I have not yet tested if a slightly older version of prd.py would work without the error, if so, I'll add an edit to this report.

EDIT: older Versions of prd.py also produce the error

**Comment by DeliciousPi2745** [comment]
Seconding - I just encountered the same thing on windows. I ran a couple of prompts successfully but then started getting this error every time. If it's relevant, the error first appeared for me after I downloaded ViTL16 & RN50x4; they appear to have downloaded successfully but every run I've attempted afterwards has thrown the same error. I was previously simply using ViTB32 & RN50.

I don't know if this is relevant, but the only other setting I can think of that I changed in between runs is CGS; I tried setting it to 18000 from auto along with the new models.

OS: Windows 10 Education, 21H1
GPU/VRAM: RTX 2070 Super, 8 GB (not ideal, I know, but I still prefer it to colab :) )
CUDA/Torchvision: Cuda 11.7 & Torchvision 0.11.3+cu113

**Comment by lowfuel** [comment]
Try setting symmetry scale to a schedule. This would match the current value you have but in schedule form:
```
[20000]*1000
```
I recently changed this to use a schedule, but the UI might still be treating it as an integer.

**Comment by KnoBuddy** [comment]
Symmetry Scale was changed to a schedule in a recent update to PRD and you must input a script in schedule form. It was a quick fix, I haven't decided the final implementation. Ideally it will accept both schedules and just a plain value.

**Comment by KnoBuddy** [comment]
Also, those other branches are not intended for anyone to use and are for my development purposes only. Obviously it's public, do as you please, but whatever is up there please don't report bugs on those branches.

**Comment by WorldTeacher** [comment]
> Try setting symmetry scale to a schedule. This would match the current value you have but in schedule form:
> 
> ```
> [20000]*1000
> ```
> 
> I recently changed this to use a schedule, but the UI might still be treating it as an integer.

changing it to this fixed the error
